### ISSUE TITLE
Exception when using config file

### ISSUE THREAD

**Issue by schnatterer** [cloudogu/gitops-playground#166]
Tested on  8ae976a0, images built locally

Config file
```
features: 
  argocd: 
    emailFrom: from@argo.cd
    emailToAdmin: to-admin@argo.cd
    emailToUser: to-user@argo.cd
  monitoring: 
    grafanaEmailFrom: from@grafa.na
    grafanaEmailTo: to@grafa.na
```

Dev-image works:
```
docker build -t gitops-playground:dev --build-arg ENV=dev  --progress=plain .    

 docker run --rm  -u $(id -u) \
    -v ~/.config/k3d/kubeconfig-gitops-playground.yaml:/home/.kube/config \
  -v $PWD/config.yaml:/config/config.yaml \
    --net=host \
   gitops-playground:dev --yes --argocd --base-url=http://localhost --mail --metrics -x --config-file=/config/config.yaml
```

Build graal native image fails:
```
docker build -t gitops-playground  --progress=plain .                                                 

docker run --rm --pull=always -u $(id -u) \
    -v ~/.config/k3d/kubeconfig-gitops-playground.yaml:/home/.kube/config \
  -v $PWD/config.yaml:/config/config.yaml \
    --net=host \
   gitops-playground --yes --argocd --base-url=http://localhost --mail   --metrics -x --config-file=/config/config.yaml


com.networknt.schema.JsonMetaSchema - Could not load validator type
com.networknt.schema.JsonSchemaException: java.lang.NoSuchMethodException: com.networknt.schema.TypeValidator.<init>(java.lang.String, com.fasterxml.jackson.databind.JsonNode, com.networknt.schema.JsonSchema, com.networknt.schema.ValidationContext)
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:290)
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:63)
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:295)
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:615)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:388)
        at com.networknt.schema.BaseJsonValidator.validate(BaseJsonValidator.java:115)
        at com.cloudogu.gitops.config.schema.JsonSchemaValidator.validate(JsonSchemaValidator.groovy:20)
        at com.cloudogu.gitops.config.ApplicationConfigurator.setConfig(ApplicationConfigurator.groovy:196)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCli.getConfig(GitopsPlaygroundCli.groovy:210)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCli.run(GitopsPlaygroundCli.groovy:174)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCliMain.executionStrategy(GitopsPlaygroundCliMain.groovy:23)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCliMain.exec(GitopsPlaygroundCliMain.groovy:35)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCliMain.main(GitopsPlaygroundCliMain.groovy:13)
Caused by: java.lang.NoSuchMethodException: com.networknt.schema.TypeValidator.<init>(java.lang.String, com.fasterxml.jackson.databind.JsonNode, com.networknt.schema.JsonSchema, com.networknt.schema.ValidationContext)
        at java.base@17.0.5/java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.base@17.0.5/java.lang.Class.getConstructor(DynamicHub.java:2271)
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:160)
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:278)
```

**Comment by schnatterer** [comment]
Maybe related, printing the config file also fails

```
docker run --rm -t  -u $(id -u) \
    -v ~/.config/k3d/kubeconfig-gitops-playground.yaml:/home/.kube/config \
    --net=host \
    gitops-playground --output-config-file
```
Result:
```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public java.lang.Object[] org.codehaus.groovy.runtime.GStringImpl.getValues()
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.base@17.0.5/java.lang.reflect.Method.acquireMethodAccessor(Method.java:71)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:566)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4522)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4475)
        at com.cloudogu.gitops.config.ConfigToConfigFileConverter.convert(ConfigToConfigFileConverter.groovy:17)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCli.run(GitopsPlaygroundCli.groovy:198)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCliMain.exec(GitopsPlaygroundCliMain.groovy:25)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCliMain.main(GitopsPlaygroundCliMain.groovy:13)
```

**Comment by schnatterer** [comment]
After checking the [second comment](#issuecomment-1969198788)`, regarding `--output-config-file` is unrelated.
